### ISSUE TITLE
Invalid XML should not break parsing when IsSuppressingErrors = true

### ISSUE THREAD

**Issue by cmxl** [AngleSharp/AngleSharp.Xml#14]
# Bug Report

## Prerequisites

- [&check;] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [&check;] Are you running the latest version of AngleSharp?
- [&check;] Did you check the FAQs to see if that helps you?
- [&check;] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [&check;] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

When using `IsSuppressingErrors = true` in XmlParserOptions an exception is thrown when trying to parse an invalid XML.

The Stacktrace:
```
AngleSharp.Xml.Parser.XmlParseException: Error while parsing the provided XML document.
   at AngleSharp.Xml.Parser.XmlTokenizer.TagSelfClosing(XmlTagToken tag)
   at AngleSharp.Xml.Parser.XmlDomBuilder.ParseAsync(XmlParserOptions options, CancellationToken cancelToken)
   at AngleSharp.Xml.Parser.XmlParser.ParseAsync(XmlDocument document, CancellationToken cancel)
```

## Steps to Reproduce
Given the following XML:
```xml
<P>
    <P>
        <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000"></FONT>
    </P>
    <P>
        <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000"></FONT>
    </P>
    <P>
        <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#0000ff">
            <U>
                <https://some.url.example.com></U>
            </FONT>
            <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000">
                <B></B>
            </FONT>
            <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000"></FONT>
        </P>
        <P>
            <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000"></FONT>
        </P>
        <P>
            <FONT FACE="calibri" SIZE="14.666666666666666" COLOR="#000000"></FONT>
        </P>
    </P>
```

The problem is the missing closing tag of the first `<P>`.
When parsing the xml like so, the exception from the description above is thrown:
```c#
var xml = "xml from above";
var config = Configuration
                    .Default
                    .WithXml();
var context = BrowsingContext.New(config);

var parser = new XmlParser(new XmlParserOptions { IsSuppressingErrors = true }, context);
var document = await parser.ParseDocumentAsync(xml, cancellationToken);
var html = document.ToHtml();
```

I know this sounds quite stupid, but I need to actually parse invalid XML data and convert it to HTML afterwards.
Is there some way to parse and/or fix an invalid XML with AngleSharp.Xml?

**Comment by cmxl** [comment]
As of writing maybe it is not the `<P>` tag, but the wierd `<https://some.url.example.com>`. I'll check this and come back here again

**Comment by cmxl** [comment]
Ok it's actually just the `<https://some.url.example.com>` !
But how would I parse this?

**Comment by FlorianRappl** [comment]
Hm the problem here is that this is actually touching part of the spec where there is no proper fallback.

Where is the XML file usually consumed? Because it would not pass through anything that takes proper XML. Maybe its consumed by some (X)HTML parser?
