### ISSUE TITLE
Parser ignoring IsKeepingSourceReferences

### ISSUE THREAD

**Issue by dompagoj** [AngleSharp/AngleSharp.Xml#16]
# Bug Report

## Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [x] Did you perform a search in the issues?

## Description

Running the parser with XmlParserOptions() { IsKeepingSourceReferences = true, } doesn't actually keep the source references, i looked into the source code and while the HtmlParser checks IsKeepingSourceReferences and assignes the source reference correctly as can be seen here
![image](https://user-images.githubusercontent.com/40147233/156220384-ff61763a-b309-4d1e-8b62-fd2c3d2c0fc8.png)

The xml parser never does that, meaning IElement.SourceReference is always null

## Steps to Reproduce

1. Create a XmlParser with XmlParserOptions() { IsKeepingSourceReferences = true, }
2. Run Parse

**Expected behavior: IElements should have SourceReference set

**Actual behavior: SourceReference is always null

**Environment details: Linux, .NET 6

## Possible Solution
Look into how the HtmlDomBuilder handles it and possibly just copy it, (don't know much about the repo so probably just ignore what i said)

**Comment by FlorianRappl** [comment]
Yeah good point - should be implemented.

**Comment by FlorianRappl** [comment]
Landed in `devel`.
