### ISSUE TITLE
When an attribute already exists, SetAttribute adds a second copy with the new value, instead of updating the existing one

### ISSUE THREAD

**Issue by oscar-h64** [AngleSharp/AngleSharp.Xml#26]
# Bug Report

## Prerequisites

- [X] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [X] Are you running the latest version of AngleSharp?
- [X] Did you check the FAQs to see if that helps you?
- [X] Are you reporting to the correct repository? (there are multiple AngleSharp libraries, e.g., `AngleSharp.Css` for CSS support)
- [X] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

## Description

(I hope I'm reporting this in the correct repo - apologies if not!)

If I use `IElement.SetAttribute` for an attribute that already exists, it adds a new duplicate attribute with the new value, leaving the existing attribute as is with its original value.

The expected behaviour (at least by how I read the docs) is that the existing attribute should be modified with the new value.

If there is no existing attribute everything works as expected.

## Steps to Reproduce

MWE:

```c#
// in csproj, no other deps: <PackageReference Include="AngleSharp.Xml" Version="1.0.0" />

using AngleSharp.Xml;
using AngleSharp.Xml.Parser;

const string xlinkHref = "xlink:href";

var input = "<use xlink:href=\"#original\"></use>";

var xmlParser = new XmlParser();

var parsed = xmlParser.ParseDocument(input);

Console.WriteLine("Original xlink:href: {0}", parsed.Children[0].GetAttribute(xlinkHref));

// Uncomment for expected behaviour
//parsed.Children[0].RemoveAttribute(xlinkHref);

// SetAttribute docs:
// > Adds a new attribute or changes the value of an existing attribute on the specified element.
// > Params:
// > - name – The name of the attribute as a string.
// > - value – The desired new value of the attribute.
parsed.Children[0].SetAttribute(xlinkHref, "#new");

// Should be "#new"
Console.WriteLine("New xlink:href: {0}", parsed.Children[0].GetAttribute(xlinkHref));

// Single use element should have a single `xlink:href` attribute with value #new
Console.WriteLine("Final output: {0}", parsed.ToXml());
```

**Expected behavior:**

```
Original xlink:href: #original
New xlink:href: #new
Final output: <use xlink:href="#new"></use>
```

**Actual behavior:**

```
Original xlink:href: #original
New xlink:href: #original
Final output: <use xlink:href="#original" xlink:href="#new"></use>
```

**Environment details:** Linux, .NET 8

## Possible Solution

(no familiar enough with the library to have anything useful to contribute)

**Comment by oscar-h64** [comment]
So to add some extra information to this. It works fine for attributes without the namespace. The namespacing in my example is obviously invalid so here's a better example with what I think is valid XML:

```c#
using AngleSharp.Xml;
using AngleSharp.Xml.Parser;

const string xlinkHref = "xlink:href";

var input = "<svg xmlns=\"http://www.w3.org/2000/svg\" xmlns:xlink=\"http://www.w3.org/1999/xlink\" ><use xlink:href=\"#original\"></use></svg>";

var xmlParser = new XmlParser();

var parsed = xmlParser.ParseDocument(input);

Console.WriteLine("Original xlink:href: {0}", parsed.Children[0].Children[0].GetAttribute(xlinkHref));

// SetAttribute docs:
// > Adds a new attribute or changes the value of an existing attribute on the specified element.
// > Params:
// > - name – The name of the attribute as a string.
// > - value – The desired new value of the attribute.
parsed.Children[0].Children[0].SetAttribute("http://www.w3.org/1999/xlink", "href", "#new");

// Should be "#new"
Console.WriteLine("New xlink:href: {0}", parsed.Children[0].Children[0].GetAttribute(xlinkHref));

// Single use element should have a single `xlink:href` attribute with value #new
Console.WriteLine("Final output: {0}", parsed.ToXml());
```

This still fails.

If as the second argument to `SetAttribute` we use `xlink:href` then things work as expected, so is it expecting a prefixed attribute name, as well as specifying the namespace?

More confusingly, we found we could put any string (except null/empty string) as the namespace, and it would still replace the attribute as expected, which seemed odd it seems to ignore it when using the no-namespace version failed.

Very possible that we're missing something obvious here, and we're just misusing it, but something doesn't seem right.

**Comment by FlorianRappl** [comment]
Yes you need to denote both: https://devdoc.net/web/developer.mozilla.org/en-US/docs/DOM/element.setAttributeNS.html

I guess MDN / the DOM API is your friend here.

Hope that clears it out. Let me know if you have more questions.

Unfortunately I have not designed the DOM API nor can I control your feelings here. We just need to live with what we have.

**Comment by oscar-h64** [comment]
Thanks for the reply - I hadn't clocked that the API was designed to match that.

It's not mentioned on the devdoc version, but on the raw Mozilla version it does clarify this function has special behaviour https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttributeNS

> setAttributeNS is the only method for namespaced attributes which expects the fully qualified name, i.e. "namespace:localname"

I'm guessing because unlike other functions this one takes the fully qualified name, it actually just disregards the namespace argument, hence the accepting any string?

Happy for this to be closed anyway, as it's behaving as specified.

**Comment by FlorianRappl** [comment]
> Thanks for the reply - I hadn't clocked that the API was designed to match that.

Yes it's one of AngleSharp's design principles.

> I'm guessing because unlike other functions this one takes the fully qualified name, it actually just disregards the namespace argument, hence the accepting any string?

Yup that's how it works. I'd say that this is because the whole DOM API comes from HTML which barely touches namespaces (even though they surely are possible / used). Hence it's not really namespace-friendly.
