### ISSUE TITLE
Allow to suppress '<' validation for attribute values when error suppression is enabled

### ISSUE THREAD

**Issue by kasthack** [AngleSharp/AngleSharp.Xml#6]
### Description

Allow to bypass opening bracket validation when XmlParserOptions.IsSuppressingErrors is set to true. [Just a single-line change](https://github.com/AngleSharp/AngleSharp.Xml/compare/master...kasthack:patch-1#diff-44c9cfd1f6d143ab142b67fe320b7c2dR1049)

### Background

> Provide any additional background for the feature. e.g., user scenarios.

Parsing technically malformed XML-elements that contain opening diamond brackets in attributes.

* This is a somewhat [known issue](https://www.google.com/search?&q=0x3C%2C+is+an+invalid+attribute+character&oq=0x3C%2C+is+an+invalid+attribute+character)
* '<' handling is buried [deep](https://github.com/dotnet/corefx/blob/df5bba114e23afc4a3621917da0a1f810be19e7a/src/System.Private.Xml/src/System/Xml/Core/XmlTextReaderImpl.cs#L5181) in .net's built-in System.Xml.XmlReader, so invalid documents can't be parsed without writing a substantial amount of code.
* Correcting the input on the fly basically requires writing an own tokenizer which seems quite excessive for something as simple as ignoring an opening bracket that should be escaped.
* Documentation for XmlParserOptions.IsSuppressingErrors [explicitly states](https://github.com/AngleSharp/AngleSharp.Xml/blob/master/src/AngleSharp.Xml/Parser/XmlParserOptions.cs#L14), that enabling this option may break the document and it's disabled by default anyway, so changing this behavior won't be an unpleasant surprise for the users.

Currently, trying to parse `<condition value="a < b" />` [would raise an exception](https://github.com/AngleSharp/AngleSharp.Xml/blob/master/src/AngleSharp.Xml/Parser/XmlTokenizer.cs#L1049) even if error suppression is enabled. Proposed change would allow to successfully parse it.

**Comment by FlorianRappl** [comment]
Sounds great. Could you make the PR @kasthack ? Then we could fit it in 0.13!

Thanks a lot :beers:!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
