### ISSUE TITLE
Poor invalid entity reference handling in attributes

### ISSUE THREAD

**Issue by kasthack** [AngleSharp/AngleSharp.Xml#9]
### Prerequisites

- [x] Can you reproduce the problem in a [MWE](https://en.wikipedia.org/wiki/Minimal_working_example)?
- [x] Are you running the latest version of AngleSharp?
- [x] Did you check the FAQs to see if that helps you?
- [x] Are you reporting to the correct repository? (if its an issue with the core library, please report to `AngleSharp` directly)
- [x] Did you perform a search in the issues?

For more information, see the `CONTRIBUTING` guide.

### Description

^ title

### Steps to Reproduce

1. Try to parse `<foo bar="&#34" baz="123"/>` with `IsSuppressingErrors = true`

**Expected behavior:**
* Tag gets parsed
* `bar` attribute contains `"` or at least `&#34`

**Actual behavior:**

`XmlParserException` gets thrown

### Possible Solution

PR #8

**Comment by FlorianRappl** [comment]
Yep I think in this mode we should be far more relaxed. Good catch!

**Comment by FlorianRappl** [comment]
Landed in `devel`.
